(global-set-key (kbd "C-x RET") 'compile)
(global-set-key (kbd "M-/") 'undo-tree-redo)
(global-set-key (kbd "C-.") 'imenu)
(global-set-key (kbd "C-x l") 'ibuffer)
(global-set-key (kbd "C-x f") 'find-file-at-point)
